In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
colors = ['Red', 'Green', 'Blue']
encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
colors_2d = np.array(colors).reshape(-1, 1)
one_hot_encoded = encoder.fit_transform(colors_2d)
print(one_hot_encoded)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
