In [19]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense


In [20]:
text = "Please contact me in the future"
chars = sorted(list(set(text)))
char_to_index = {char: i for i, char in enumerate(chars)}
index_to_char = {i: char for i, char in enumerate(chars)}


In [21]:
char_to_index

{' ': 0,
 'P': 1,
 'a': 2,
 'c': 3,
 'e': 4,
 'f': 5,
 'h': 6,
 'i': 7,
 'l': 8,
 'm': 9,
 'n': 10,
 'o': 11,
 'r': 12,
 's': 13,
 't': 14,
 'u': 15}

In [22]:
index_to_char

{0: ' ',
 1: 'P',
 2: 'a',
 3: 'c',
 4: 'e',
 5: 'f',
 6: 'h',
 7: 'i',
 8: 'l',
 9: 'm',
 10: 'n',
 11: 'o',
 12: 'r',
 13: 's',
 14: 't',
 15: 'u'}

In [23]:
seq_length = 3
sequences = []
labels = []

for i in range(len(text) - seq_length):
	seq = text[i:i+seq_length]
	label = text[i+seq_length]
	sequences.append([char_to_index[char] for char in seq])
	labels.append(char_to_index[label])


In [24]:
labels

[2,
 13,
 4,
 0,
 3,
 11,
 10,
 14,
 2,
 3,
 14,
 0,
 9,
 4,
 0,
 7,
 10,
 0,
 14,
 6,
 4,
 0,
 5,
 15,
 14,
 15,
 12,
 4]

In [25]:
sequences

[[1, 8, 4],
 [8, 4, 2],
 [4, 2, 13],
 [2, 13, 4],
 [13, 4, 0],
 [4, 0, 3],
 [0, 3, 11],
 [3, 11, 10],
 [11, 10, 14],
 [10, 14, 2],
 [14, 2, 3],
 [2, 3, 14],
 [3, 14, 0],
 [14, 0, 9],
 [0, 9, 4],
 [9, 4, 0],
 [4, 0, 7],
 [0, 7, 10],
 [7, 10, 0],
 [10, 0, 14],
 [0, 14, 6],
 [14, 6, 4],
 [6, 4, 0],
 [4, 0, 5],
 [0, 5, 15],
 [5, 15, 14],
 [15, 14, 15],
 [14, 15, 12]]

In [26]:
X = np.array(sequences)
y = np.array(labels)

X_one_hot = tf.one_hot(X, len(chars))
y_one_hot = tf.one_hot(y, len(chars))


In [27]:
X

array([[ 1,  8,  4],
       [ 8,  4,  2],
       [ 4,  2, 13],
       [ 2, 13,  4],
       [13,  4,  0],
       [ 4,  0,  3],
       [ 0,  3, 11],
       [ 3, 11, 10],
       [11, 10, 14],
       [10, 14,  2],
       [14,  2,  3],
       [ 2,  3, 14],
       [ 3, 14,  0],
       [14,  0,  9],
       [ 0,  9,  4],
       [ 9,  4,  0],
       [ 4,  0,  7],
       [ 0,  7, 10],
       [ 7, 10,  0],
       [10,  0, 14],
       [ 0, 14,  6],
       [14,  6,  4],
       [ 6,  4,  0],
       [ 4,  0,  5],
       [ 0,  5, 15],
       [ 5, 15, 14],
       [15, 14, 15],
       [14, 15, 12]])

In [28]:
y

array([ 2, 13,  4,  0,  3, 11, 10, 14,  2,  3, 14,  0,  9,  4,  0,  7, 10,
        0, 14,  6,  4,  0,  5, 15, 14, 15, 12,  4])

In [29]:
X_one_hot

<tf.Tensor: shape=(28, 3, 16), dtype=float32, numpy=
array([[[0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 1., 0.]],

       [[0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.]],

       [[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)>

In [30]:
y_one_hot

<tf.Tensor: shape=(28, 16), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
 

In [31]:
model = Sequential()
model.add(SimpleRNN(50, input_shape=(seq_length, len(chars)), activation='relu'))
model.add(Dense(len(chars), activation='softmax'))


In [32]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [33]:
model.fit(X_one_hot, y_one_hot, epochs=100)


Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 2.7331 - accuracy: 0.0714
Epoch 2/100
1/1 [==============================] - 0s 14ms/step - loss: 2.7136 - accuracy: 0.0714
Epoch 3/100
1/1 [==============================] - 0s 12ms/step - loss: 2.6945 - accuracy: 0.0714
Epoch 4/100
1/1 [==============================] - 0s 12ms/step - loss: 2.6754 - accuracy: 0.1429
Epoch 5/100
1/1 [==============================] - 0s 12ms/step - loss: 2.6567 - accuracy: 0.1429
Epoch 6/100
1/1 [==============================] - 0s 12ms/step - loss: 2.6382 - accuracy: 0.1429
Epoch 7/100
1/1 [==============================] - 0s 11ms/step - loss: 2.6198 - accuracy: 0.1786
Epoch 8/100
1/1 [==============================] - 0s 12ms/step - loss: 2.6016 - accuracy: 0.2500
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 2.5832 - accuracy: 0.2500
Epoch 10/100
1/1 [==============================] - 0s 12ms/step - loss: 2.5647 - accuracy: 0.3214
Epoch 11/100
1/1 [===

In [35]:
start_seq = "Please contact "
generated_text = start_seq

for i in range(50):
	x = np.array([[char_to_index[char] for char in generated_text[-seq_length:]]])
	x_one_hot = tf.one_hot(x, len(chars))
	prediction = model.predict(x_one_hot)
	next_index = np.argmax(prediction)
	next_char = index_to_char[next_index]
	generated_text += next_char

print("Generated Text:")
print(generated_text)


1/1 [==============================] - 0s 24ms/step
Generated Text:
Please contact me in the future contact me in the future contact 


In [36]:
# Assuming you have a separate test set (X_test, y_test) for evaluation
# If you don't have a separate test set, you can use a validation set or split your data accordingly

# Evaluate the model on the test set
evaluation_results = model.evaluate(X_one_hot, y_one_hot)

# Print the evaluation results
print("Evaluation Loss:", evaluation_results[0])
print("Evaluation Accuracy:", evaluation_results[1])


1/1 [==============================] - 0s 310ms/step - loss: 0.4568 - accuracy: 1.0000
Evaluation Loss: 0.4568287432193756
Evaluation Accuracy: 1.0
